### PR TITLE
mark bugs as IN_PROGRESS when not RESOLVED

### PR DESCRIPTION
**Pull request by arthurzam**
Resolves: #46

### CODE REVIEW

**Review by thesamesam — APPROVED** [review]

**Comment by arthurzam** [comment]
Just as a note, I have applied that patch in my `/etc/portage/patches/` to see if it works well during today's various AT bugs handling, and it worked as intended.

**Review by mgorny — COMMENTED** [review]
I think you should really record new tapes rather than modifying them by hand. Just remove these two tapes, start the docker by `make -C test/bugzilla-instance run` and let pytest update them.

**Comment by arthurzam** [comment]
> I think you should really record new tapes rather than modifying them by hand. Just remove these two tapes, start the docker by `make -C test/bugzilla-instance run` and let pytest update them.

This was my first time using that docker for bugzilla instance (which is very nice, btw) - all my previous tests were against our real bugzilla instance - lesson learned.

This was also my first time using `vcr` tests rerecording. It was somewhat weird. I have removed those 2 files and rerun and it recreated them, but other various variable changed - hope those were done correctly.

**Review by mgorny — APPROVED** [review]
Thanks!

**Pull request closed without merging**
